"""FactType taxonomy enum definitions for Athena cognitive engine."""

from enum import Enum

class FactType(Enum):
    """Predefined categories of raw, objective facts extracted from observations."""
    PRICE_OPEN = "PRICE_OPEN"
    PRICE_HIGH = "PRICE_HIGH"
    PRICE_LOW = "PRICE_LOW"
    PRICE_CLOSE = "PRICE_CLOSE"
    PRICE_VOLUME = "PRICE_VOLUME"
    PRICE_TIMEFRAME = "PRICE_TIMEFRAME"
    PRICE_CLOSE_GT_OPEN = "PRICE_CLOSE_GT_OPEN"
    PRICE_DAILY_RANGE = "PRICE_DAILY_RANGE"
    
    FINANCIAL_REVENUE = "FINANCIAL_REVENUE"
    FINANCIAL_NET_INCOME = "FINANCIAL_NET_INCOME"
    FINANCIAL_EBITDA = "FINANCIAL_EBITDA"
    FINANCIAL_ASSETS = "FINANCIAL_ASSETS"
    FINANCIAL_LIABILITIES = "FINANCIAL_LIABILITIES"
    FINANCIAL_EQUITY = "FINANCIAL_EQUITY"
    FINANCIAL_DEBT = "FINANCIAL_DEBT"
    
    MACRO_INDICATOR_VALUE = "MACRO_INDICATOR_VALUE"
    NEWS_PUBLICATION_METADATA = "NEWS_PUBLICATION_METADATA"

    # Technical indicator outputs — produced by core/intelligence/engine.py
    INDICATOR_SMA         = "INDICATOR_SMA"
    INDICATOR_EMA         = "INDICATOR_EMA"
    INDICATOR_WILDER      = "INDICATOR_WILDER"
    INDICATOR_RSI         = "INDICATOR_RSI"
    INDICATOR_MACD        = "INDICATOR_MACD"
    INDICATOR_MACD_SIGNAL = "INDICATOR_MACD_SIGNAL"
    INDICATOR_MACD_HIST   = "INDICATOR_MACD_HIST"
    INDICATOR_ATR         = "INDICATOR_ATR"
    INDICATOR_BB_UPPER    = "INDICATOR_BB_UPPER"
    INDICATOR_BB_MIDDLE   = "INDICATOR_BB_MIDDLE"
    INDICATOR_BB_LOWER    = "INDICATOR_BB_LOWER"
    INDICATOR_VWAP        = "INDICATOR_VWAP"
    INDICATOR_MOMENTUM    = "INDICATOR_MOMENTUM"
    INDICATOR_ROC         = "INDICATOR_ROC"
    INDICATOR_VOLUME_TREND = "INDICATOR_VOLUME_TREND"
