"""Common utilities, types, and validation helpers for Athena domain models."""

from core.domain.common.identifiers import (
    CandidateId,
    CompanyId,
    DecisionId,
    DomainId,
    EventId,
    EvidenceId,
    ExchangeId,
    FactId,
    HypothesisId,
    InferenceId,
    LearningId,
    MarketId,
    MarketImpactId,
    ObservationId,
    OutcomeId,
    SecurityId,
    SignalId,
    ThesisId,
)
from core.domain.common.metadata import DomainMetadata
from core.domain.common.validation import (
    validate_non_empty_string,
    validate_non_negative,
    validate_positive,
    validate_range,
)

__all__ = [
    "DomainId",
    "MarketId",
    "ExchangeId",
    "CompanyId",
    "SecurityId",
    "ObservationId",
    "SignalId",
    "EvidenceId",
    "InferenceId",
    "HypothesisId",
    "ThesisId",
    "DecisionId",
    "OutcomeId",
    "LearningId",
    "EventId",
    "MarketImpactId",
    "FactId",
    "CandidateId",
    "DomainMetadata",
    "validate_positive",
    "validate_non_negative",
    "validate_range",
    "validate_non_empty_string",
]
